
GET http://testnet.newrl.net:8182/get-last-block-index
GET http://testnet.newrl.net:8182/get-node-wallet-address
GET http://testnet.newrl.net:8182/get-miners
GET http://testnet.newrl.net:8182/get-peers
GET http://testnet.newrl.net:8182/download-chain
GET http://testnet.newrl.net:8182/download-state
POST http://testnet.newrl.net:8182/run-updater
POST http://testnet.newrl.net:8182/revert-chain?block_index=1&propogate=false

GET http://makemyfund.in:8182/get-last-block-index
GET http://makemyfund.in:8182/get-node-wallet-address
GET http://makemyfund.in:8182/get-miners
GET http://makemyfund.in:8182/get-peers
POST http://makemyfund.in:8182/run-updater
POST http://makemyfund.in:8182/revert-chain?block_index=1&propogate=false

GET http://asqisys.com:8182/get-last-block-index
GET http://asqisys.com:8182/get-node-wallet-address
GET http://asqisys.com:8182/get-miners
GET http://asqisys.com:8182/get-peers
POST http://asqisys.com:8182/run-updater
GET http://asqisys.com:8182/download-chain
POST http://asqisys.com:8182/revert-chain?block_index=1&propogate=false

GET http://159.223.163.198:8182/get-last-block-index
GET http://159.223.163.198:8182/get-node-wallet-address
GET http://159.223.163.198:8182/get-miners
GET http://159.223.163.198:8182/get-peers
POST http://159.223.163.198:8182/run-updater
POST http://159.223.163.198:8182/revert-chain?block_index=10&propogate=false
POST http://159.223.163.198:8182/run-updater

GET http://localhost:8182/get-last-block-index
GET http://localhost:8182/get-node-wallet-address
GET http://localhost:8182/get-miners
GET http://localhost:8182/get-peers
POST http://localhost:8182/run-updater
GET http://localhost:8182/download-chain
POST http://localhost:8182/revert-chain?block_index=1&propogate=false
POST http://localhost:8182/sync-chain-from-peers
POST http://localhost:8182/receive-receipt

{"receipt": {
    "data": {
        "block_index": 11,
        "block_hash": "f31d89bd40e32b9c78f0a55b8772c0773a95e1fa27cc5d72c5de8e2e505ddd38",
        "vote": 1
    },
    "public_key": "pGVqHZ8AhE4r7ddXa05dowU9HSMWrv7gnT/zfVEq3TtkMC7bLhuXMYf40m0u91qdMT9vqpEdBRBqq6xHw7AX2w==",
    "signature": "ujvehs42Ob1pviaJd/yqbhsr+s4n0V0ucH8duY+mWGWJtYrZigxubaKiRvXQMiHluMh25zasHxGcIP1DVli6pg=="
}}

POST http://testnet.newrl.net:8182/update-software?propogate=true
POST http://159.223.163.198:8182/update-software?propogate=true
POST http://asqisys.com:8182/update-software?propogate=true
POST http://makemyfund.in:8182/update-software?propogate=false
POST http://localhost:8182/update-software?propogate=true

POST http://159.223.163.198:8182/sync-chain-from-peers

POST http://testnet.newrl.net:8182/revert-chain?block_index=1&propogate=false
POST http://159.223.163.198:8182/revert-chain?block_index=1&propogate=false
POST http://asqisys.com:8182/revert-chain?block_index=1&propogate=false
POST http://makemyfund.in:8182/revert-chain?block_index=1&propogate=false
POST http://localhost:8182/revert-chain?block_index=1&propogate=false

POST http://testnet.newrl.net:8182/run-updater?add_to_chain_before_consensus=true